version: "3.9"

services:
  mysql:
    image: mysql:5.7.38
    container_name: mysql
    hostname: mysql
    restart: always
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bookstore
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u",
          "user",
          "-ppassword",
          "-e",
          "SELECT 1"
        ]
      timeout: 20s
      retries: 10
    volumes:
      - ./localdb/bookstore:/docker-entrypoint-initdb.d
