version: "3.9"

services:
  bookstore-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: bookstore-api
    restart: always
    command: "./main"
    ports:
      - "8080:8080"
    env_file:
      - .env
