// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// BookstoreController is an autogenerated mock type for the BookstoreController type
type BookstoreController struct {
	mock.Mock
}

// ListBooks provides a mock function with given fields: w, r
func (_m *BookstoreController) ListBooks(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewBookstoreController creates a new instance of BookstoreController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookstoreController(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookstoreController {
	mock := &BookstoreController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
