// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HealthCheckController is an autogenerated mock type for the HealthCheckController type
type HealthCheckController struct {
	mock.Mock
}

// Ping provides a mock function with given fields: w, r
func (_m *HealthCheckController) Ping(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewHealthCheckController creates a new instance of HealthCheckController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheckController(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheckController {
	mock := &HealthCheckController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
