// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PingRepository is an autogenerated mock type for the PingRepository type
type PingRepository struct {
	mock.Mock
}

// Ping provides a mock function with given fields:
func (_m *PingRepository) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPingRepository creates a new instance of PingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PingRepository {
	mock := &PingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
