name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    GO_VERSION: 1.19.x
    TERM: xterm

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: 
              uses: actions/setup-go@v3
              with:
                go-version: ${{ env.GO_VERSION }}
            - name: Run unit tests
              run: make test
