name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Run unit tests
              run: make test
